### ISSUE TITLE
Running code using open-interpreter duplicates app

### ISSUE THREAD

**Issue by Notnaton** [jbexta/AgentPilot#10]
using open-interpreter:
"Write a hello world program in python"
`print("hello world")`

Agent pilot spawns new windows forever. and runs the code multiple times.

**Comment by jbexta** [comment]
Will investigate, it seems to be for any print, thanks for letting me know 👍

**Comment by jbexta** [comment]
This is fixed for me in version 0.1.0, but I just noticed auto run code doesn't work, will bring out patch versions soon
