### ISSUE TITLE
BUG: AgentPilot AppImage Fails to Run with libGL driver errors (Ubuntu 22.04)

### ISSUE THREAD

**Issue by mruderman** [jbexta/AgentPilot#18]
**Preface:**

This bug report is an experiment. I used open interpreter to generate a summary of our session trying to fool around with the AppImage trying to get it to work. Below is the output of my request to generate a helpful reproducible bug report.

The caveat is that I'm not technical enough to assess meaningfully how helpful or informative any of the diagnostics or potential problem solving.

I'm curious as to your feedback, as a developer, whether something like this is useful (in this strange year of 2024 where this is even possible). Additionally, if there is anything I could as a standard procedure ask OI to capture in generating bug reports (that would make the report more useful) please let me know as well.

If this isn't helpful at all, I apologize for any inconvenience. Thank you for your development efforts as always.

**Open Interpreter Summary:**

The AppImage for AgentPilot 0.1.5 on Ubuntu 22.04 fails with a libGL error related to the bundled libstdc++.so.6 library.

**Steps to Reproduce:**

1. Download the AppImage for AgentPilot 0.1.5.
2. Make it executable and try to run:

```
chmod a+x ./AgentPilot-0.1.5_88131536057e4e2ddbb84f9520a16a9e.AppImage
./AgentPilot-0.1.5_88131536057e4e2ddbb84f9520a16a9e.AppImage --verbose
```

3. Observe the error.

**Expected Behavior:**

The AppImage should start the AgentPilot software without any errors related to OpenGL drivers or the C++ standard library.

**Actual Behavior:**

Running the AppImage results in the following error:

```
libGL error: failed to open iris: /tmp/_MEIlb4Bq8/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/x86_64-linux-gnu/dri/iris_dri.so)
libGL error: failed to load driver: iris
libGL error: failed to open swrast: /tmp/_MEIlb4Bq8/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /usr/lib/x86_64-linux-gnu/dri/swrast_dri.so)
libGL error: failed to load driver: swrast
```

The AppImage does not run successfully.

**Environment:**

- OS: Ubuntu 22.04
- AppImage: AgentPilot 0.1.5

**Investigation:**

The libstdc++.so.6 within the AppImage seems to lack GLIBCXX_3.4.29, which is required by iris_dri.so and swrast_dri.so OpenGL drivers. However, the system's libstdc++.so.6 does provide GLIBCXX_3.4.29.

Even trying to set the LIBGL_DRIVERS_PATH before running the AppImage does not help, making it seem as though the bundled libstdc++.so.6 might be causing the problem.

```
LIBGL_DRIVERS_PATH=/usr/lib/x86_64-linux-gnu/dri ./AgentPilot-0.1.5_88131536057e4e2ddbb84f9520a16a9e.AppImage --verbose
```

**Proposed Solution (from OpenInterpreter):**

The AppImage should either avoid bundling libstdc++.so.6 (to rely on the system's version) or include a newer version of libstdc++.so.6 that provides GLIBCXX_3.4.29. Given that the system libraries are capable of providing the necessary versions, it may be best for the AppImage not to bundle libstdc++.so.6 and instead utilize the versions available on the user's system. This should allow the AppImage to coexist with the system's OpenGL drivers.

**Comment by mruderman** [comment]
Can confirm it now works under Ubuntu 22.04! I also proposed a minor edit to the ReadMe for AppImageLauncher users.

**Comment by jbexta** [comment]
I'll get it released asap, I'm getting a segfault error again way too often, this has come and gone for a month, I keep thinking I've fixed it then it comes back. But I've got it reproducible now, so hopefully I can get this fixed for good, I can't see any edits btw

**Comment by jbexta** [comment]
I'm getting a segfault error again way too often, I'm gona try to fix this before doing a full release. It's unrelated to this opengl issue, it's come and gone for a month, I keep thinking I've fixed it then it comes back. But I've got it reproducible now, so hopefully I can get this fixed for good, I can't see any edits btw

**Comment by jbexta** [comment]
Finally fixed the segfault, two headache bugs that's been haunting me for a while, thanks again mruderman!
