### ISSUE TITLE
UX Issues

### ISSUE THREAD

**Issue by chymian** [jbexta/AgentPilot#23]
testing the new 0.1.7:

1. the display needs a dark/light toggle & adapt to the system.
   i.e. I'm an expat in asia and love to sit outside. Apps without light-mode are just not readable during the day.
2. the display-settings tab needs a reset button.
3. startup error on missing `configuration.yaml`

**Comment by jbexta** [comment]
Ok I'll see what I can do, I'll probably add an option to change system text color.
The config.yaml will be removed on next major version 0.2.0 and merged into the DB, and if there's no data.db file then one will be created, so the only file that will be distributed is the executable

**Comment by jbexta** [comment]
Sorted this in v2, text color can be changed and all icons use text color, any other issues feel free to let us know
