### ISSUE TITLE
Error on launch (Arch Linux)

### ISSUE THREAD

**Issue by Only1337** [jbexta/AgentPilot#8]
The error output I received is as follows:

```
╭─only@only in ~/AgentPilot-0.0.9_Portable_Linux_x64 as 🧙 took 1s
[🔴] × /home/only/AgentPilot-0.0.9_Portable_Linux_x64/main
```

```
None
sys.executable: /home/only/AgentPilot-0.0.9_Portable_Linux_x64/main
dirname of os.path.abspath(sys.executable): /home/only/AgentPilot-0.0.9_Portable_Linux_x64
dirname of os.path.abspath(__file__): /tmp/_MEIoLX1Yq/agentpilot/utils
dirname of os.path.abspath(os.path.dirname(__file__)): /tmp/_MEIoLX1Yq/agentpilot
None
sys.executable: /home/only/AgentPilot-0.0.9_Portable_Linux_x64/main
dirname of os.path.abspath(sys.executable): /home/only/AgentPilot-0.0.9_Portable_Linux_x64
dirname of os.path.abspath(__file__): /tmp/_MEIoLX1Yq/agentpilot/utils
dirname of os.path.abspath(os.path.dirname(__file__)): /tmp/_MEIoLX1Yq/agentpilot
None
sys.executable: /home/only/AgentPilot-0.0.9_Portable_Linux_x64/main
dirname of os.path.abspath(sys.executable): /home/only/AgentPilot-0.0.9_Portable_Linux_x64
dirname of os.path.abspath(__file__): /tmp/_MEIoLX1Yq/agentpilot/utils
dirname of os.path.abspath(os.path.dirname(__file__)): /tmp/_MEIoLX1Yq/agentpilot
None
sys.executable: /home/only/AgentPilot-0.0.9_Portable_Linux_x64/main
dirname of os.path.abspath(sys.executable): /home/only/AgentPilot-0.0.9_Portable_Linux_x64
dirname of os.path.abspath(__file__): /tmp/_MEIoLX1Yq/agentpilot/utils
dirname of os.path.abspath(os.path.dirname(__file__)): /tmp/_MEIoLX1Yq/agentpilot
Traceback (most recent call last):
File "agentpilot/__main__.py", line 270, in <module>
File "agentpilot/__main__.py", line 266, in main
File "agentpilot/gui.py", line 3816, in run
File "agentpilot/gui.py", line 3608, in __init__
File "agentpilot/gui.py", line 3254, in __init__
File "agentpilot/gui.py", line 3286, in __init__
AttributeError: PySide6.QtWidgets.QPushButton.__init__(): 'icon' is not a Qt property or a signal
[273433] Failed to execute script '__main__' due to unhandled exception!
```

**Comment by jbexta** [comment]
Which version of arch linux are you runnin?

**Comment by Only1337** [comment]
OS: Garuda Linux x86_64
Kernel: 6.5.8-zen1-1-zen
Shell: bash 5.1.16
Resolution: 1920x1080
DE: Plasma 5.27.8
WM: kwin
WM Theme: PureSketch
Theme: [Plasma], Sweet-Dark [GTK3]
Icons: candy-icons [Plasma], candy-icons [GTK2/3]
Terminal: konsole
Terminal Font: FiraCode Nerd Font Mono 12
CPU: Intel i7-8700 (12) @ 4.600GHz
GPU: AMD ATI Radeon RX 580 2048SP
Memory: 3310MiB / 15929MiB

I have not installed Arch Linux directly, but the distribution I use, Garuda Linux, is based on Arch and is very close to Arch

**Comment by jbexta** [comment]
It's like it's trying to use an older version of pyqt, which is strange. I just posted an updated version, if you try and see what it does, it might work or it might give a different error, if it gives a different error let us know what it says

**Comment by jbexta** [comment]
Yea they are just debug info, next version will be AppImage and won't display terminal 👍

**Comment by Only1337** [comment]
Thank you for your interest in me. Honestly, I've needed such a tool since I saw Windows Copilot. I congratulate you for taking on the responsibility of this great project. I hope that new participants will join this project in the future and the project will be developed.
